### ISSUE TITLE
plugin make refactor -> rename failed.

### ISSUE THREAD

**Issue by yvvw** [pontem-network/intellij-move#62]
![image](https://user-images.githubusercontent.com/15168529/184048345-255a35c9-d575-475d-9bb3-0e4796dc606f.png)
webstorm version WebStorm 2022.2 Build #WS-222.3345.108, built on July 23, 2022
plugin version 1.15.0.222
I reseted ide to default configuration. rename file failed after install this plugin.

```log
2022-08-11 08:31:55,874 [ 197230]   INFO - #c.i.u.i.UnindexedFilesUpdater - Performing delayed pushing properties tasks for aletheia took 0ms; general responsiveness: ok; EDT responsiveness: ok
2022-08-11 08:31:55,887 [ 197243]   INFO - #c.i.u.i.UnindexedFilesUpdater - Scanning of aletheia uses 15 scanning threads
2022-08-11 08:31:55,984 [ 197340]   INFO - #o.m.c.MoveProjectsService - Project state refresh started
2022-08-11 08:31:55,995 [ 197351]   INFO - #c.i.u.i.FileBasedIndexImpl - Rebuild requested for index MvNamedElementIndex
java.lang.Throwable
	at com.intellij.util.indexing.FileBasedIndex.requestRebuild(FileBasedIndex.java:101)
	at org.move.ide.inspections.imports.MoveElementsIndex$Companion.requestRebuild(MoveElementsIndex.kt:39)
	at org.move.cli.MoveProjectsService$resetIDEState$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$13(ApplicationImpl.java:1032)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1032)
	at org.move.cli.MoveProjectsService$resetIDEState$1.invoke(MoveProjectsService.kt:239)
	at org.move.cli.MoveProjectsService$resetIDEState$1.invoke(MoveProjectsService.kt:155)
	at com.intellij.openapi.application.ActionsKt$invokeAndWaitIfNeeded$$inlined$computeDelegated$lambda$1.run(actions.kt:33)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-08-11 08:31:55,998 [ 197354]   INFO - #c.i.u.i.UnindexedFilesUpdater - Cancelled indexing of aletheia
2022-08-11 08:31:55,998 [ 197354]   INFO - #c.i.u.i.UnindexedFilesUpdater - Started scanning for indexing of aletheia. Reason: Reindex requested by project root model changes
2022-08-11 08:31:55,998 [ 197354]   INFO - #c.i.u.i.UnindexedFilesUpdater - Performing delayed pushing properties tasks for aletheia took 0ms; general responsiveness: ok; EDT responsiveness: ok
2022-08-11 08:31:56,011 [ 197367]   INFO - #c.i.u.i.UnindexedFilesUpdater - Scanning of aletheia uses 15 scanning threads
```

**Comment by mkurnikov** [comment]
What do you mean by "invalid"?

**Comment by yvvw** [comment]
rename failed

**Comment by mkurnikov** [comment]
I don't think this `Throwable` log is relevant, could you tell me how to reproduce it? 

Also, rename of the module file also renames the underlying module automatically, so it can fail if you choose the invalid name of the file, i.e. `module.move`.

**Comment by yvvw** [comment]
![GIF 2022-8-12 9-39-26](https://user-images.githubusercontent.com/15168529/184269893-67cd1cd9-f78f-4cac-a981-fb79530f7e58.gif)

**Comment by mkurnikov** [comment]
I reproduced it, thanks! I'll add a fix in the next version, which will be released Mon-Tue.
